services:
  auth-server:
    container_name: auth-server
    image: domboeckli/spring-6-auth-server:0.0.3-SNAPSHOT
    ports:
      - "9000:9000"
    expose:
      - 9000
    environment:
      SPRING_SECURITY_OAUTH2_AUTHORIZATION_SERVER_ISSUER: http://localhost:9000
      
  busybox:
    image: busybox:1.37.0
    container_name: busybox
    depends_on:
      auth-server:
        condition: service_started
        required: true
    healthcheck:
      test: [ "CMD", "sh", "-c", "
            echo 'Checking BusyBox readiness...' &&
            test -f /bin/sh &&
            wget -qO- http://auth-server:9000/actuator/health/readiness | grep -q '\"status\":\"UP\"'
          " ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      /bin/sh -c '
      while true; do
        auth_health=$$(wget -q -O - http://auth-server:9000/actuator/health/readiness 2>/dev/null)

        echo "{
          \"timestamp\": \"$$(date -Iseconds)\",
          \"services\": {
            \"auth-server\": $$auth_health
          }
        }"

        sleep 10
      done
      '            
