### List Beers
GET http://localhost:8082/api/v2/beer
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJraWQiOiIyMjVmMDU0My1kMDJlLTQzMDMtOTE3MC05MGM0NDcyMTkxMmYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc3NzcyMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzc4MDIwLCJpYXQiOjE3MzI3Nzc3MjAsImp0aSI6IjU5ZjI4ZGFiLTBhZWUtNDM4MS1hNTZiLTdhMzAzOTY1MDFmMSJ9.T40SgTxO2avVoSVAGNaUdWY30YRdbkkvMJKpD-sTtKkwKVS1VoH5F6Dvx12UN1CWjalgC1cOsX9K4wgHV4fV3FCslKaH-MG1pXhkTQx8F9NH7x2_EiyB9AMpU4J3BZQibLoIKvVh--3D39ZMTNJ8x94LvKytjqlML78XavVU1S0tuQPrelQb0RLjkySyLEteyPoL0aYlfT9M7qA6pIR-PH2Du50ZHoWnF-7dWU1zYlYuTQbGSvNh1cksVCeSFexq5Xk7uZpWUS9jaXgK7bLhzBppYKDjNdChq7KQL8TKXXnOe1N2YWmyQyFkWJZZNGCdTfJC_UdhOPAsj-P8RaE8Qw

### Get Beer by ID
GET http://localhost:8082/api/v2/beer/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJraWQiOiIyMjVmMDU0My1kMDJlLTQzMDMtOTE3MC05MGM0NDcyMTkxMmYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc3NzcyMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzc4MDIwLCJpYXQiOjE3MzI3Nzc3MjAsImp0aSI6IjU5ZjI4ZGFiLTBhZWUtNDM4MS1hNTZiLTdhMzAzOTY1MDFmMSJ9.T40SgTxO2avVoSVAGNaUdWY30YRdbkkvMJKpD-sTtKkwKVS1VoH5F6Dvx12UN1CWjalgC1cOsX9K4wgHV4fV3FCslKaH-MG1pXhkTQx8F9NH7x2_EiyB9AMpU4J3BZQibLoIKvVh--3D39ZMTNJ8x94LvKytjqlML78XavVU1S0tuQPrelQb0RLjkySyLEteyPoL0aYlfT9M7qA6pIR-PH2Du50ZHoWnF-7dWU1zYlYuTQbGSvNh1cksVCeSFexq5Xk7uZpWUS9jaXgK7bLhzBppYKDjNdChq7KQL8TKXXnOe1N2YWmyQyFkWJZZNGCdTfJC_UdhOPAsj-P8RaE8Qw

### Create Beer
POST http://localhost:8082/api/v2/beer
Accept: application/json
Authorization: Bearer eyJraWQiOiIyMjVmMDU0My1kMDJlLTQzMDMtOTE3MC05MGM0NDcyMTkxMmYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc3NzcyMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzc4MDIwLCJpYXQiOjE3MzI3Nzc3MjAsImp0aSI6IjU5ZjI4ZGFiLTBhZWUtNDM4MS1hNTZiLTdhMzAzOTY1MDFmMSJ9.T40SgTxO2avVoSVAGNaUdWY30YRdbkkvMJKpD-sTtKkwKVS1VoH5F6Dvx12UN1CWjalgC1cOsX9K4wgHV4fV3FCslKaH-MG1pXhkTQx8F9NH7x2_EiyB9AMpU4J3BZQibLoIKvVh--3D39ZMTNJ8x94LvKytjqlML78XavVU1S0tuQPrelQb0RLjkySyLEteyPoL0aYlfT9M7qA6pIR-PH2Du50ZHoWnF-7dWU1zYlYuTQbGSvNh1cksVCeSFexq5Xk7uZpWUS9jaXgK7bLhzBppYKDjNdChq7KQL8TKXXnOe1N2YWmyQyFkWJZZNGCdTfJC_UdhOPAsj-P8RaE8Qw
Content-Type: application/json

{
    "beerName": "presidente",
    "beerStyle": "LAGER",
    "upc": "xx",
    "quantityOnHand": 5,
    "price": 27.16
}

### Create Beer returns BAD REQUEST, beerName is to short
POST http://localhost:8082/api/v2/beer
Accept: application/json
Authorization: Bearer eyJraWQiOiIyMjVmMDU0My1kMDJlLTQzMDMtOTE3MC05MGM0NDcyMTkxMmYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc3NzcyMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzc4MDIwLCJpYXQiOjE3MzI3Nzc3MjAsImp0aSI6IjU5ZjI4ZGFiLTBhZWUtNDM4MS1hNTZiLTdhMzAzOTY1MDFmMSJ9.T40SgTxO2avVoSVAGNaUdWY30YRdbkkvMJKpD-sTtKkwKVS1VoH5F6Dvx12UN1CWjalgC1cOsX9K4wgHV4fV3FCslKaH-MG1pXhkTQx8F9NH7x2_EiyB9AMpU4J3BZQibLoIKvVh--3D39ZMTNJ8x94LvKytjqlML78XavVU1S0tuQPrelQb0RLjkySyLEteyPoL0aYlfT9M7qA6pIR-PH2Du50ZHoWnF-7dWU1zYlYuTQbGSvNh1cksVCeSFexq5Xk7uZpWUS9jaXgK7bLhzBppYKDjNdChq7KQL8TKXXnOe1N2YWmyQyFkWJZZNGCdTfJC_UdhOPAsj-P8RaE8Qw
Content-Type: application/json

{
    "beerName": "p",
    "beerStyle": "LAGER",
    "upc": "xx",
    "quantityOnHand": 5,
    "price": 27.16
}

### Update Beer by ID
PUT http://localhost:8082/api/v2/beer/1
Accept: application/json
Authorization: Bearer eyJraWQiOiIyMjVmMDU0My1kMDJlLTQzMDMtOTE3MC05MGM0NDcyMTkxMmYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc3NzcyMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzc4MDIwLCJpYXQiOjE3MzI3Nzc3MjAsImp0aSI6IjU5ZjI4ZGFiLTBhZWUtNDM4MS1hNTZiLTdhMzAzOTY1MDFmMSJ9.T40SgTxO2avVoSVAGNaUdWY30YRdbkkvMJKpD-sTtKkwKVS1VoH5F6Dvx12UN1CWjalgC1cOsX9K4wgHV4fV3FCslKaH-MG1pXhkTQx8F9NH7x2_EiyB9AMpU4J3BZQibLoIKvVh--3D39ZMTNJ8x94LvKytjqlML78XavVU1S0tuQPrelQb0RLjkySyLEteyPoL0aYlfT9M7qA6pIR-PH2Du50ZHoWnF-7dWU1zYlYuTQbGSvNh1cksVCeSFexq5Xk7uZpWUS9jaXgK7bLhzBppYKDjNdChq7KQL8TKXXnOe1N2YWmyQyFkWJZZNGCdTfJC_UdhOPAsj-P8RaE8Qw
Content-Type: application/json

{
    "beerName": "presidenteEdited",
    "beerStyle": "LAGER",
    "upc": "xx",
    "quantityOnHand": 5,
    "price": 27.16
}

### Update Beer by ID returns BAD REQUEST, beerStyle is empty
PUT http://localhost:8082/api/v2/beer/1
Accept: application/json
Authorization: Bearer eyJraWQiOiIyMjVmMDU0My1kMDJlLTQzMDMtOTE3MC05MGM0NDcyMTkxMmYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc3NzcyMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzc4MDIwLCJpYXQiOjE3MzI3Nzc3MjAsImp0aSI6IjU5ZjI4ZGFiLTBhZWUtNDM4MS1hNTZiLTdhMzAzOTY1MDFmMSJ9.T40SgTxO2avVoSVAGNaUdWY30YRdbkkvMJKpD-sTtKkwKVS1VoH5F6Dvx12UN1CWjalgC1cOsX9K4wgHV4fV3FCslKaH-MG1pXhkTQx8F9NH7x2_EiyB9AMpU4J3BZQibLoIKvVh--3D39ZMTNJ8x94LvKytjqlML78XavVU1S0tuQPrelQb0RLjkySyLEteyPoL0aYlfT9M7qA6pIR-PH2Du50ZHoWnF-7dWU1zYlYuTQbGSvNh1cksVCeSFexq5Xk7uZpWUS9jaXgK7bLhzBppYKDjNdChq7KQL8TKXXnOe1N2YWmyQyFkWJZZNGCdTfJC_UdhOPAsj-P8RaE8Qw
Content-Type: application/json

{
    "beerName": "presidenteEdited",
    "beerStyle": "",
    "upc": "xx",
    "quantityOnHand": 5,
    "price": 27.16
}

### Patch Beer by ID
PUT http://localhost:8082/api/v2/beer/1
Accept: application/json
Authorization: Bearer eyJraWQiOiIyMjVmMDU0My1kMDJlLTQzMDMtOTE3MC05MGM0NDcyMTkxMmYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc3NzcyMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzc4MDIwLCJpYXQiOjE3MzI3Nzc3MjAsImp0aSI6IjU5ZjI4ZGFiLTBhZWUtNDM4MS1hNTZiLTdhMzAzOTY1MDFmMSJ9.T40SgTxO2avVoSVAGNaUdWY30YRdbkkvMJKpD-sTtKkwKVS1VoH5F6Dvx12UN1CWjalgC1cOsX9K4wgHV4fV3FCslKaH-MG1pXhkTQx8F9NH7x2_EiyB9AMpU4J3BZQibLoIKvVh--3D39ZMTNJ8x94LvKytjqlML78XavVU1S0tuQPrelQb0RLjkySyLEteyPoL0aYlfT9M7qA6pIR-PH2Du50ZHoWnF-7dWU1zYlYuTQbGSvNh1cksVCeSFexq5Xk7uZpWUS9jaXgK7bLhzBppYKDjNdChq7KQL8TKXXnOe1N2YWmyQyFkWJZZNGCdTfJC_UdhOPAsj-P8RaE8Qw
Content-Type: application/json

{
    "beerName": "presidentePatched",
    "beerStyle": "LAGER",
    "upc": "xx",
    "quantityOnHand": 5,
    "price": 27.16
}

### Patch Beer by ID. Beername is missing
PUT http://localhost:8082/api/v2/beer/1
Accept: application/json
Authorization: Bearer eyJraWQiOiIyMjVmMDU0My1kMDJlLTQzMDMtOTE3MC05MGM0NDcyMTkxMmYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc3NzcyMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzc4MDIwLCJpYXQiOjE3MzI3Nzc3MjAsImp0aSI6IjU5ZjI4ZGFiLTBhZWUtNDM4MS1hNTZiLTdhMzAzOTY1MDFmMSJ9.T40SgTxO2avVoSVAGNaUdWY30YRdbkkvMJKpD-sTtKkwKVS1VoH5F6Dvx12UN1CWjalgC1cOsX9K4wgHV4fV3FCslKaH-MG1pXhkTQx8F9NH7x2_EiyB9AMpU4J3BZQibLoIKvVh--3D39ZMTNJ8x94LvKytjqlML78XavVU1S0tuQPrelQb0RLjkySyLEteyPoL0aYlfT9M7qA6pIR-PH2Du50ZHoWnF-7dWU1zYlYuTQbGSvNh1cksVCeSFexq5Xk7uZpWUS9jaXgK7bLhzBppYKDjNdChq7KQL8TKXXnOe1N2YWmyQyFkWJZZNGCdTfJC_UdhOPAsj-P8RaE8Qw
Content-Type: application/json

{
    "beerStyle": "LAGER",
    "upc": "xx",
    "quantityOnHand": 5,
    "price": 27.16
}

### Delete Beer by ID
DELETE http://localhost:8082/api/v2/beer/1
Accept: application/json
Authorization: Bearer eyJraWQiOiIyMjVmMDU0My1kMDJlLTQzMDMtOTE3MC05MGM0NDcyMTkxMmYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTczMjc3NzcyMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNzMyNzc4MDIwLCJpYXQiOjE3MzI3Nzc3MjAsImp0aSI6IjU5ZjI4ZGFiLTBhZWUtNDM4MS1hNTZiLTdhMzAzOTY1MDFmMSJ9.T40SgTxO2avVoSVAGNaUdWY30YRdbkkvMJKpD-sTtKkwKVS1VoH5F6Dvx12UN1CWjalgC1cOsX9K4wgHV4fV3FCslKaH-MG1pXhkTQx8F9NH7x2_EiyB9AMpU4J3BZQibLoIKvVh--3D39ZMTNJ8x94LvKytjqlML78XavVU1S0tuQPrelQb0RLjkySyLEteyPoL0aYlfT9M7qA6pIR-PH2Du50ZHoWnF-7dWU1zYlYuTQbGSvNh1cksVCeSFexq5Xk7uZpWUS9jaXgK7bLhzBppYKDjNdChq7KQL8TKXXnOe1N2YWmyQyFkWJZZNGCdTfJC_UdhOPAsj-P8RaE8Qw
