### List Customers
GET http://localhost:{{application-port}}/api/v2/customer
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### Get Customer by ID
GET http://localhost:{{application-port}}/api/v2/customer/1
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json

### Create Customer
POST http://localhost:{{application-port}}/api/v2/customer
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json

{
    "customerName": "Ich bin neu"
}

### Create Customer returns BAD REQUEST, customerName is to short
POST http://localhost:{{application-port}}/api/v2/customer
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json

{
    "customerName": "p"
}

### Update Customer by ID
PUT http://localhost:{{application-port}}/api/v2/customer/1
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json

{
    "customerName": "newCustomerName"
}

### Update Customer by ID returns BAD REQUEST, customerName is empty
PUT http://localhost:{{application-port}}/api/v2/customer/1
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json

{
    "customerName": ""
}

### Patch Customer by ID
PUT http://localhost:{{application-port}}/api/v2/customer/1
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json

{
    "customerName": "patchedCustomerName"
}

### Patch Customer by ID. Customername is too short
PUT http://localhost:{{application-port}}/api/v2/customer/1
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
Content-Type: application/json

{
    "customerName": ""
}

### Delete Customer by ID
DELETE http://localhost:{{application-port}}/api/v2/customer/1
Accept: application/json
Authorization: Bearer {{$auth.token("auth-id")}}
